# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_UI_demo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 573)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(10, 120, 121, 182))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_106 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_106.setMinimumSize(QtCore.QSize(40, 0))
        self.label_106.setAlignment(QtCore.Qt.AlignCenter)
        self.label_106.setObjectName("label_106")
        self.gridLayout_13.addWidget(self.label_106, 4, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_102.setMinimumSize(QtCore.QSize(40, 0))
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.gridLayout_13.addWidget(self.label_102, 0, 0, 1, 1)
        self.INDY_JNT_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.INDY_JNT_1.setReadOnly(True)
        self.INDY_JNT_1.setObjectName("INDY_JNT_1")
        self.gridLayout_13.addWidget(self.INDY_JNT_1, 0, 1, 1, 1)
        self.INDY_JNT_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.INDY_JNT_2.setReadOnly(True)
        self.INDY_JNT_2.setObjectName("INDY_JNT_2")
        self.gridLayout_13.addWidget(self.INDY_JNT_2, 1, 1, 1, 1)
        self.INDY_JNT_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.INDY_JNT_3.setReadOnly(True)
        self.INDY_JNT_3.setObjectName("INDY_JNT_3")
        self.gridLayout_13.addWidget(self.INDY_JNT_3, 2, 1, 1, 1)
        self.INDY_JNT_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.INDY_JNT_5.setReadOnly(True)
        self.INDY_JNT_5.setObjectName("INDY_JNT_5")
        self.gridLayout_13.addWidget(self.INDY_JNT_5, 4, 1, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_105.setMinimumSize(QtCore.QSize(40, 0))
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName("label_105")
        self.gridLayout_13.addWidget(self.label_105, 2, 0, 1, 1)
        self.INDY_JNT_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.INDY_JNT_6.setReadOnly(True)
        self.INDY_JNT_6.setObjectName("INDY_JNT_6")
        self.gridLayout_13.addWidget(self.INDY_JNT_6, 5, 1, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_107.setMinimumSize(QtCore.QSize(40, 0))
        self.label_107.setAlignment(QtCore.Qt.AlignCenter)
        self.label_107.setObjectName("label_107")
        self.gridLayout_13.addWidget(self.label_107, 5, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_104.setMinimumSize(QtCore.QSize(40, 0))
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName("label_104")
        self.gridLayout_13.addWidget(self.label_104, 3, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_103.setMinimumSize(QtCore.QSize(40, 0))
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.gridLayout_13.addWidget(self.label_103, 1, 0, 1, 1)
        self.INDY_JNT_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.INDY_JNT_4.setReadOnly(True)
        self.INDY_JNT_4.setObjectName("INDY_JNT_4")
        self.gridLayout_13.addWidget(self.INDY_JNT_4, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(140, 120, 121, 182))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_140 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_140.setMinimumSize(QtCore.QSize(40, 0))
        self.label_140.setAlignment(QtCore.Qt.AlignCenter)
        self.label_140.setObjectName("label_140")
        self.gridLayout_14.addWidget(self.label_140, 4, 0, 1, 1)
        self.label_141 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_141.setMinimumSize(QtCore.QSize(40, 0))
        self.label_141.setAlignment(QtCore.Qt.AlignCenter)
        self.label_141.setObjectName("label_141")
        self.gridLayout_14.addWidget(self.label_141, 5, 0, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_117.setMinimumSize(QtCore.QSize(40, 0))
        self.label_117.setAlignment(QtCore.Qt.AlignCenter)
        self.label_117.setObjectName("label_117")
        self.gridLayout_14.addWidget(self.label_117, 0, 0, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_122.setMinimumSize(QtCore.QSize(40, 0))
        self.label_122.setAlignment(QtCore.Qt.AlignCenter)
        self.label_122.setObjectName("label_122")
        self.gridLayout_14.addWidget(self.label_122, 1, 0, 1, 1)
        self.label_139 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_139.setMinimumSize(QtCore.QSize(40, 0))
        self.label_139.setAlignment(QtCore.Qt.AlignCenter)
        self.label_139.setObjectName("label_139")
        self.gridLayout_14.addWidget(self.label_139, 3, 0, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_127.setMinimumSize(QtCore.QSize(40, 0))
        self.label_127.setAlignment(QtCore.Qt.AlignCenter)
        self.label_127.setObjectName("label_127")
        self.gridLayout_14.addWidget(self.label_127, 2, 0, 1, 1)
        self.INDY_TCP_X = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.INDY_TCP_X.setReadOnly(True)
        self.INDY_TCP_X.setObjectName("INDY_TCP_X")
        self.gridLayout_14.addWidget(self.INDY_TCP_X, 0, 1, 1, 1)
        self.INDY_TCP_Y = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.INDY_TCP_Y.setReadOnly(True)
        self.INDY_TCP_Y.setObjectName("INDY_TCP_Y")
        self.gridLayout_14.addWidget(self.INDY_TCP_Y, 1, 1, 1, 1)
        self.INDY_TCP_Z = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.INDY_TCP_Z.setReadOnly(True)
        self.INDY_TCP_Z.setObjectName("INDY_TCP_Z")
        self.gridLayout_14.addWidget(self.INDY_TCP_Z, 2, 1, 1, 1)
        self.INDY_TCP_RX = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.INDY_TCP_RX.setReadOnly(True)
        self.INDY_TCP_RX.setObjectName("INDY_TCP_RX")
        self.gridLayout_14.addWidget(self.INDY_TCP_RX, 3, 1, 1, 1)
        self.INDY_TCP_RY = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.INDY_TCP_RY.setReadOnly(True)
        self.INDY_TCP_RY.setObjectName("INDY_TCP_RY")
        self.gridLayout_14.addWidget(self.INDY_TCP_RY, 4, 1, 1, 1)
        self.INDY_TCP_RZ = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.INDY_TCP_RZ.setReadOnly(True)
        self.INDY_TCP_RZ.setObjectName("INDY_TCP_RZ")
        self.gridLayout_14.addWidget(self.INDY_TCP_RZ, 5, 1, 1, 1)
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(270, 120, 121, 182))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_95 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_95.setMinimumSize(QtCore.QSize(40, 0))
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.gridLayout_15.addWidget(self.label_95, 4, 0, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_112.setMinimumSize(QtCore.QSize(40, 0))
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.gridLayout_15.addWidget(self.label_112, 5, 0, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_113.setMinimumSize(QtCore.QSize(40, 0))
        self.label_113.setAlignment(QtCore.Qt.AlignCenter)
        self.label_113.setObjectName("label_113")
        self.gridLayout_15.addWidget(self.label_113, 0, 0, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_114.setMinimumSize(QtCore.QSize(40, 0))
        self.label_114.setAlignment(QtCore.Qt.AlignCenter)
        self.label_114.setObjectName("label_114")
        self.gridLayout_15.addWidget(self.label_114, 1, 0, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_115.setMinimumSize(QtCore.QSize(40, 0))
        self.label_115.setAlignment(QtCore.Qt.AlignCenter)
        self.label_115.setObjectName("label_115")
        self.gridLayout_15.addWidget(self.label_115, 3, 0, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_116.setMinimumSize(QtCore.QSize(40, 0))
        self.label_116.setAlignment(QtCore.Qt.AlignCenter)
        self.label_116.setObjectName("label_116")
        self.gridLayout_15.addWidget(self.label_116, 2, 0, 1, 1)
        self.RB_JNT_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.RB_JNT_1.setReadOnly(True)
        self.RB_JNT_1.setObjectName("RB_JNT_1")
        self.gridLayout_15.addWidget(self.RB_JNT_1, 0, 1, 1, 1)
        self.RB_JNT_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.RB_JNT_2.setReadOnly(True)
        self.RB_JNT_2.setObjectName("RB_JNT_2")
        self.gridLayout_15.addWidget(self.RB_JNT_2, 1, 1, 1, 1)
        self.RB_JNT_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.RB_JNT_3.setReadOnly(True)
        self.RB_JNT_3.setObjectName("RB_JNT_3")
        self.gridLayout_15.addWidget(self.RB_JNT_3, 2, 1, 1, 1)
        self.RB_JNT_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.RB_JNT_4.setReadOnly(True)
        self.RB_JNT_4.setObjectName("RB_JNT_4")
        self.gridLayout_15.addWidget(self.RB_JNT_4, 3, 1, 1, 1)
        self.RB_JNT_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.RB_JNT_5.setReadOnly(True)
        self.RB_JNT_5.setObjectName("RB_JNT_5")
        self.gridLayout_15.addWidget(self.RB_JNT_5, 4, 1, 1, 1)
        self.RB_JNT_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.RB_JNT_6.setReadOnly(True)
        self.RB_JNT_6.setObjectName("RB_JNT_6")
        self.gridLayout_15.addWidget(self.RB_JNT_6, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(270, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(400, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(400, 120, 121, 182))
        self.gridLayoutWidget_16.setObjectName("gridLayoutWidget_16")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_97 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_97.setMinimumSize(QtCore.QSize(40, 0))
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.gridLayout_16.addWidget(self.label_97, 4, 0, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_118.setMinimumSize(QtCore.QSize(40, 0))
        self.label_118.setAlignment(QtCore.Qt.AlignCenter)
        self.label_118.setObjectName("label_118")
        self.gridLayout_16.addWidget(self.label_118, 0, 0, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_119.setMinimumSize(QtCore.QSize(40, 0))
        self.label_119.setAlignment(QtCore.Qt.AlignCenter)
        self.label_119.setObjectName("label_119")
        self.gridLayout_16.addWidget(self.label_119, 1, 0, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_120.setMinimumSize(QtCore.QSize(40, 0))
        self.label_120.setAlignment(QtCore.Qt.AlignCenter)
        self.label_120.setObjectName("label_120")
        self.gridLayout_16.addWidget(self.label_120, 3, 0, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_121.setMinimumSize(QtCore.QSize(40, 0))
        self.label_121.setAlignment(QtCore.Qt.AlignCenter)
        self.label_121.setObjectName("label_121")
        self.gridLayout_16.addWidget(self.label_121, 2, 0, 1, 1)
        self.RB_TCP_X = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.RB_TCP_X.setReadOnly(True)
        self.RB_TCP_X.setObjectName("RB_TCP_X")
        self.gridLayout_16.addWidget(self.RB_TCP_X, 0, 1, 1, 1)
        self.RB_TCP_Y = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.RB_TCP_Y.setReadOnly(True)
        self.RB_TCP_Y.setObjectName("RB_TCP_Y")
        self.gridLayout_16.addWidget(self.RB_TCP_Y, 1, 1, 1, 1)
        self.RB_TCP_Z = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.RB_TCP_Z.setReadOnly(True)
        self.RB_TCP_Z.setObjectName("RB_TCP_Z")
        self.gridLayout_16.addWidget(self.RB_TCP_Z, 2, 1, 1, 1)
        self.RB_TCP_RX = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.RB_TCP_RX.setReadOnly(True)
        self.RB_TCP_RX.setObjectName("RB_TCP_RX")
        self.gridLayout_16.addWidget(self.RB_TCP_RX, 3, 1, 1, 1)
        self.RB_TCP_RY = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.RB_TCP_RY.setReadOnly(True)
        self.RB_TCP_RY.setObjectName("RB_TCP_RY")
        self.gridLayout_16.addWidget(self.RB_TCP_RY, 4, 1, 1, 1)
        self.RB_TCP_RZ = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.RB_TCP_RZ.setReadOnly(True)
        self.RB_TCP_RZ.setObjectName("RB_TCP_RZ")
        self.gridLayout_16.addWidget(self.RB_TCP_RZ, 5, 1, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_98.setMinimumSize(QtCore.QSize(40, 0))
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.gridLayout_16.addWidget(self.label_98, 5, 0, 1, 1)
        self.BTN_MOTION_HALT = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_MOTION_HALT.setGeometry(QtCore.QRect(710, 260, 241, 81))
        self.BTN_MOTION_HALT.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.BTN_MOTION_HALT.setObjectName("BTN_MOTION_HALT")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(530, 120, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.INDY_ROBOT_STATE_IDLE = QtWidgets.QLineEdit(self.centralwidget)
        self.INDY_ROBOT_STATE_IDLE.setGeometry(QtCore.QRect(530, 140, 81, 31))
        self.INDY_ROBOT_STATE_IDLE.setAlignment(QtCore.Qt.AlignCenter)
        self.INDY_ROBOT_STATE_IDLE.setReadOnly(True)
        self.INDY_ROBOT_STATE_IDLE.setObjectName("INDY_ROBOT_STATE_IDLE")
        self.INDY_ROBOT_STATE_MOVING = QtWidgets.QLineEdit(self.centralwidget)
        self.INDY_ROBOT_STATE_MOVING.setGeometry(QtCore.QRect(530, 170, 81, 31))
        self.INDY_ROBOT_STATE_MOVING.setAlignment(QtCore.Qt.AlignCenter)
        self.INDY_ROBOT_STATE_MOVING.setReadOnly(True)
        self.INDY_ROBOT_STATE_MOVING.setObjectName("INDY_ROBOT_STATE_MOVING")
        self.RB_ROBOT_STATE_IDLE = QtWidgets.QLineEdit(self.centralwidget)
        self.RB_ROBOT_STATE_IDLE.setGeometry(QtCore.QRect(530, 240, 81, 31))
        self.RB_ROBOT_STATE_IDLE.setAlignment(QtCore.Qt.AlignCenter)
        self.RB_ROBOT_STATE_IDLE.setReadOnly(True)
        self.RB_ROBOT_STATE_IDLE.setObjectName("RB_ROBOT_STATE_IDLE")
        self.RB_ROBOT_STATE_MOVING = QtWidgets.QLineEdit(self.centralwidget)
        self.RB_ROBOT_STATE_MOVING.setGeometry(QtCore.QRect(530, 270, 81, 31))
        self.RB_ROBOT_STATE_MOVING.setAlignment(QtCore.Qt.AlignCenter)
        self.RB_ROBOT_STATE_MOVING.setReadOnly(True)
        self.RB_ROBOT_STATE_MOVING.setObjectName("RB_ROBOT_STATE_MOVING")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(530, 220, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.GB_NETWORK_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.GB_NETWORK_1.setGeometry(QtCore.QRect(10, 0, 511, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GB_NETWORK_1.setFont(font)
        self.GB_NETWORK_1.setObjectName("GB_NETWORK_1")
        self.BTN_MODE_RB10 = QtWidgets.QPushButton(self.GB_NETWORK_1)
        self.BTN_MODE_RB10.setGeometry(QtCore.QRect(280, 30, 201, 51))
        self.BTN_MODE_RB10.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BTN_MODE_RB10.setFont(font)
        self.BTN_MODE_RB10.setObjectName("BTN_MODE_RB10")
        self.BTN_MODE_INDY7 = QtWidgets.QPushButton(self.GB_NETWORK_1)
        self.BTN_MODE_INDY7.setGeometry(QtCore.QRect(20, 30, 201, 51))
        self.BTN_MODE_INDY7.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BTN_MODE_INDY7.setFont(font)
        self.BTN_MODE_INDY7.setObjectName("BTN_MODE_INDY7")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(610, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.POINT_SAVE_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.POINT_SAVE_BTN.setGeometry(QtCore.QRect(10, 470, 111, 41))
        self.POINT_SAVE_BTN.setObjectName("POINT_SAVE_BTN")
        self.POINT_PLAY_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.POINT_PLAY_BTN.setGeometry(QtCore.QRect(260, 430, 71, 81))
        self.POINT_PLAY_BTN.setObjectName("POINT_PLAY_BTN")
        self.POINT_DEL_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.POINT_DEL_BTN.setGeometry(QtCore.QRect(140, 470, 111, 41))
        self.POINT_DEL_BTN.setObjectName("POINT_DEL_BTN")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 330, 241, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.BTN_SEND_CMD = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_SEND_CMD.setGeometry(QtCore.QRect(170, 430, 81, 31))
        self.BTN_SEND_CMD.setObjectName("BTN_SEND_CMD")
        self.cmd_msg_box = QtWidgets.QLineEdit(self.centralwidget)
        self.cmd_msg_box.setGeometry(QtCore.QRect(10, 430, 151, 31))
        self.cmd_msg_box.setObjectName("cmd_msg_box")
        self.TEST_POINT_INDY3 = QtWidgets.QPushButton(self.centralwidget)
        self.TEST_POINT_INDY3.setGeometry(QtCore.QRect(430, 360, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TEST_POINT_INDY3.setFont(font)
        self.TEST_POINT_INDY3.setObjectName("TEST_POINT_INDY3")
        self.TEST_POINT_INDY1 = QtWidgets.QPushButton(self.centralwidget)
        self.TEST_POINT_INDY1.setGeometry(QtCore.QRect(350, 360, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TEST_POINT_INDY1.setFont(font)
        self.TEST_POINT_INDY1.setObjectName("TEST_POINT_INDY1")
        self.TEST_POINT_INDY2 = QtWidgets.QPushButton(self.centralwidget)
        self.TEST_POINT_INDY2.setGeometry(QtCore.QRect(390, 360, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TEST_POINT_INDY2.setFont(font)
        self.TEST_POINT_INDY2.setObjectName("TEST_POINT_INDY2")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(350, 330, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(350, 420, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.TEST_POINT_RB3 = QtWidgets.QPushButton(self.centralwidget)
        self.TEST_POINT_RB3.setGeometry(QtCore.QRect(430, 450, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TEST_POINT_RB3.setFont(font)
        self.TEST_POINT_RB3.setObjectName("TEST_POINT_RB3")
        self.TEST_POINT_RB1 = QtWidgets.QPushButton(self.centralwidget)
        self.TEST_POINT_RB1.setGeometry(QtCore.QRect(350, 450, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TEST_POINT_RB1.setFont(font)
        self.TEST_POINT_RB1.setObjectName("TEST_POINT_RB1")
        self.TEST_POINT_RB2 = QtWidgets.QPushButton(self.centralwidget)
        self.TEST_POINT_RB2.setGeometry(QtCore.QRect(390, 450, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TEST_POINT_RB2.setFont(font)
        self.TEST_POINT_RB2.setObjectName("TEST_POINT_RB2")
        self.VECTOR_Y_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.VECTOR_Y_PLUS.setGeometry(QtCore.QRect(510, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VECTOR_Y_PLUS.setFont(font)
        self.VECTOR_Y_PLUS.setObjectName("VECTOR_Y_PLUS")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(460, 340, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.VECTOR_X_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.VECTOR_X_PLUS.setGeometry(QtCore.QRect(470, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VECTOR_X_PLUS.setFont(font)
        self.VECTOR_X_PLUS.setObjectName("VECTOR_X_PLUS")
        self.VECTOR_Z_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.VECTOR_Z_PLUS.setGeometry(QtCore.QRect(550, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VECTOR_Z_PLUS.setFont(font)
        self.VECTOR_Z_PLUS.setObjectName("VECTOR_Z_PLUS")
        self.VECTOR_X_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.VECTOR_X_MINUS.setGeometry(QtCore.QRect(470, 400, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VECTOR_X_MINUS.setFont(font)
        self.VECTOR_X_MINUS.setObjectName("VECTOR_X_MINUS")
        self.VECTOR_Z_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.VECTOR_Z_MINUS.setGeometry(QtCore.QRect(550, 400, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VECTOR_Z_MINUS.setFont(font)
        self.VECTOR_Z_MINUS.setObjectName("VECTOR_Z_MINUS")
        self.VECTOR_Y_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.VECTOR_Y_MINUS.setGeometry(QtCore.QRect(510, 400, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VECTOR_Y_MINUS.setFont(font)
        self.VECTOR_Y_MINUS.setObjectName("VECTOR_Y_MINUS")
        self.ROTATION_RX_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.ROTATION_RX_PLUS.setGeometry(QtCore.QRect(470, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ROTATION_RX_PLUS.setFont(font)
        self.ROTATION_RX_PLUS.setObjectName("ROTATION_RX_PLUS")
        self.ROTATION_RY_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.ROTATION_RY_MINUS.setGeometry(QtCore.QRect(510, 490, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ROTATION_RY_MINUS.setFont(font)
        self.ROTATION_RY_MINUS.setObjectName("ROTATION_RY_MINUS")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(470, 430, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.ROTATION_RZ_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.ROTATION_RZ_PLUS.setGeometry(QtCore.QRect(550, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ROTATION_RZ_PLUS.setFont(font)
        self.ROTATION_RZ_PLUS.setObjectName("ROTATION_RZ_PLUS")
        self.ROTATION_RX_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.ROTATION_RX_MINUS.setGeometry(QtCore.QRect(470, 490, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ROTATION_RX_MINUS.setFont(font)
        self.ROTATION_RX_MINUS.setObjectName("ROTATION_RX_MINUS")
        self.ROTATION_RZ_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.ROTATION_RZ_MINUS.setGeometry(QtCore.QRect(550, 490, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ROTATION_RZ_MINUS.setFont(font)
        self.ROTATION_RZ_MINUS.setObjectName("ROTATION_RZ_MINUS")
        self.ROTATION_RY_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.ROTATION_RY_PLUS.setGeometry(QtCore.QRect(510, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ROTATION_RY_PLUS.setFont(font)
        self.ROTATION_RY_PLUS.setObjectName("ROTATION_RY_PLUS")
        self.TCP_Z_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_Z_MINUS.setGeometry(QtCore.QRect(780, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_Z_MINUS.setFont(font)
        self.TCP_Z_MINUS.setObjectName("TCP_Z_MINUS")
        self.TCP_RY_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_RY_MINUS.setGeometry(QtCore.QRect(910, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_RY_MINUS.setFont(font)
        self.TCP_RY_MINUS.setObjectName("TCP_RY_MINUS")
        self.TCP_RZ_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_RZ_PLUS.setGeometry(QtCore.QRect(870, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_RZ_PLUS.setFont(font)
        self.TCP_RZ_PLUS.setObjectName("TCP_RZ_PLUS")
        self.TCP_RX_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_RX_MINUS.setGeometry(QtCore.QRect(910, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_RX_MINUS.setFont(font)
        self.TCP_RX_MINUS.setObjectName("TCP_RX_MINUS")
        self.TCP_Y_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_Y_MINUS.setGeometry(QtCore.QRect(780, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_Y_MINUS.setFont(font)
        self.TCP_Y_MINUS.setObjectName("TCP_Y_MINUS")
        self.TCP_RZ_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_RZ_MINUS.setGeometry(QtCore.QRect(910, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_RZ_MINUS.setFont(font)
        self.TCP_RZ_MINUS.setObjectName("TCP_RZ_MINUS")
        self.TCP_X_MINUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_X_MINUS.setGeometry(QtCore.QRect(780, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_X_MINUS.setFont(font)
        self.TCP_X_MINUS.setObjectName("TCP_X_MINUS")
        self.TCP_RY_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_RY_PLUS.setGeometry(QtCore.QRect(870, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_RY_PLUS.setFont(font)
        self.TCP_RY_PLUS.setObjectName("TCP_RY_PLUS")
        self.TCP_Y_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_Y_PLUS.setGeometry(QtCore.QRect(740, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_Y_PLUS.setFont(font)
        self.TCP_Y_PLUS.setObjectName("TCP_Y_PLUS")
        self.TCP_X_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_X_PLUS.setGeometry(QtCore.QRect(740, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_X_PLUS.setFont(font)
        self.TCP_X_PLUS.setObjectName("TCP_X_PLUS")
        self.TCP_RX_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_RX_PLUS.setGeometry(QtCore.QRect(870, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_RX_PLUS.setFont(font)
        self.TCP_RX_PLUS.setObjectName("TCP_RX_PLUS")
        self.TCP_Z_PLUS = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_Z_PLUS.setGeometry(QtCore.QRect(740, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TCP_Z_PLUS.setFont(font)
        self.TCP_Z_PLUS.setObjectName("TCP_Z_PLUS")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(710, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(710, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(710, 120, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(840, 120, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(840, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(840, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.OBJ_PUB_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.OBJ_PUB_BTN.setGeometry(QtCore.QRect(600, 390, 71, 111))
        self.OBJ_PUB_BTN.setObjectName("OBJ_PUB_BTN")
        self.HOME_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.HOME_BTN.setGeometry(QtCore.QRect(710, 180, 111, 71))
        self.HOME_BTN.setObjectName("HOME_BTN")
        self.ZERO_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.ZERO_BTN.setGeometry(QtCore.QRect(840, 180, 111, 71))
        self.ZERO_BTN.setObjectName("ZERO_BTN")
        self.tcp_offset_x = QtWidgets.QLineEdit(self.centralwidget)
        self.tcp_offset_x.setGeometry(QtCore.QRect(750, 390, 61, 31))
        self.tcp_offset_x.setObjectName("tcp_offset_x")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(710, 390, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(710, 360, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.TCP_OFFSET_PUB_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.TCP_OFFSET_PUB_BTN.setGeometry(QtCore.QRect(830, 390, 71, 111))
        self.TCP_OFFSET_PUB_BTN.setObjectName("TCP_OFFSET_PUB_BTN")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(710, 430, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.tcp_offset_y = QtWidgets.QLineEdit(self.centralwidget)
        self.tcp_offset_y.setGeometry(QtCore.QRect(750, 430, 61, 31))
        self.tcp_offset_y.setObjectName("tcp_offset_y")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(710, 470, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.tcp_offset_z = QtWidgets.QLineEdit(self.centralwidget)
        self.tcp_offset_z.setGeometry(QtCore.QRect(750, 470, 61, 31))
        self.tcp_offset_z.setObjectName("tcp_offset_z")
        self.PICK_N_PLACE_DEMO_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.PICK_N_PLACE_DEMO_BTN.setGeometry(QtCore.QRect(260, 330, 71, 91))
        self.PICK_N_PLACE_DEMO_BTN.setObjectName("PICK_N_PLACE_DEMO_BTN")
        self.task_control_unit = QtWidgets.QLineEdit(self.centralwidget)
        self.task_control_unit.setGeometry(QtCore.QRect(710, 150, 61, 21))
        self.task_control_unit.setObjectName("task_control_unit")
        self.GET_TASK_UNIT_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.GET_TASK_UNIT_BTN.setGeometry(QtCore.QRect(780, 150, 41, 21))
        self.GET_TASK_UNIT_BTN.setObjectName("GET_TASK_UNIT_BTN")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(570, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color: rgb(77, 237, 48);")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.COORDINATE_WORLD_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.COORDINATE_WORLD_BTN.setGeometry(QtCore.QRect(720, 20, 101, 31))
        self.COORDINATE_WORLD_BTN.setObjectName("COORDINATE_WORLD_BTN")
        self.COORDINATE_TCP_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.COORDINATE_TCP_BTN.setGeometry(QtCore.QRect(840, 20, 101, 31))
        self.COORDINATE_TCP_BTN.setObjectName("COORDINATE_TCP_BTN")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test_UI"))
        self.label_10.setText(_translate("MainWindow", "Joint Reference"))
        self.label_106.setText(_translate("MainWindow", "J5"))
        self.label_102.setText(_translate("MainWindow", "J1"))
        self.label_105.setText(_translate("MainWindow", "J3"))
        self.label_107.setText(_translate("MainWindow", "J6"))
        self.label_104.setText(_translate("MainWindow", "J4"))
        self.label_103.setText(_translate("MainWindow", "J2"))
        self.label_11.setText(_translate("MainWindow", "TCP Reference"))
        self.label_140.setText(_translate("MainWindow", "RY"))
        self.label_141.setText(_translate("MainWindow", "RZ"))
        self.label_117.setText(_translate("MainWindow", "X"))
        self.label_122.setText(_translate("MainWindow", "Y"))
        self.label_139.setText(_translate("MainWindow", "RX"))
        self.label_127.setText(_translate("MainWindow", "Z"))
        self.label_95.setText(_translate("MainWindow", "J5"))
        self.label_112.setText(_translate("MainWindow", "J6"))
        self.label_113.setText(_translate("MainWindow", "J1"))
        self.label_114.setText(_translate("MainWindow", "J2"))
        self.label_115.setText(_translate("MainWindow", "J4"))
        self.label_116.setText(_translate("MainWindow", "J3"))
        self.label_12.setText(_translate("MainWindow", "Joint Reference"))
        self.label_13.setText(_translate("MainWindow", "TCP Reference"))
        self.label_97.setText(_translate("MainWindow", "RY"))
        self.label_118.setText(_translate("MainWindow", "X"))
        self.label_119.setText(_translate("MainWindow", "Y"))
        self.label_120.setText(_translate("MainWindow", "RX"))
        self.label_121.setText(_translate("MainWindow", "Z"))
        self.label_98.setText(_translate("MainWindow", "RZ"))
        self.BTN_MOTION_HALT.setText(_translate("MainWindow", "Motion\n"
"Halt"))
        self.label_21.setText(_translate("MainWindow", "indy7 state"))
        self.INDY_ROBOT_STATE_IDLE.setText(_translate("MainWindow", "Idle"))
        self.INDY_ROBOT_STATE_MOVING.setText(_translate("MainWindow", "Moving"))
        self.RB_ROBOT_STATE_IDLE.setText(_translate("MainWindow", "Idle"))
        self.RB_ROBOT_STATE_MOVING.setText(_translate("MainWindow", "Moving"))
        self.label_22.setText(_translate("MainWindow", "rb10 state"))
        self.GB_NETWORK_1.setTitle(_translate("MainWindow", "Mode Change"))
        self.BTN_MODE_RB10.setText(_translate("MainWindow", "RB10"))
        self.BTN_MODE_INDY7.setText(_translate("MainWindow", "Indy7"))
        self.label_31.setText(_translate("MainWindow", "ROBOT"))
        self.POINT_SAVE_BTN.setText(_translate("MainWindow", "SAVE"))
        self.POINT_PLAY_BTN.setText(_translate("MainWindow", "PLAY"))
        self.POINT_DEL_BTN.setText(_translate("MainWindow", "DEL"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">way + (number) + j (or l)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">del + (number)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">go + (number)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">pick</span></p></body></html>"))
        self.BTN_SEND_CMD.setText(_translate("MainWindow", "SEND"))
        self.TEST_POINT_INDY3.setText(_translate("MainWindow", "3"))
        self.TEST_POINT_INDY1.setText(_translate("MainWindow", "1"))
        self.TEST_POINT_INDY2.setText(_translate("MainWindow", "2"))
        self.label_32.setText(_translate("MainWindow", "Indy7"))
        self.label_33.setText(_translate("MainWindow", "RB10"))
        self.TEST_POINT_RB3.setText(_translate("MainWindow", "3"))
        self.TEST_POINT_RB1.setText(_translate("MainWindow", "1"))
        self.TEST_POINT_RB2.setText(_translate("MainWindow", "2"))
        self.VECTOR_Y_PLUS.setText(_translate("MainWindow", "+"))
        self.label_34.setText(_translate("MainWindow", "Vector"))
        self.VECTOR_X_PLUS.setText(_translate("MainWindow", "+"))
        self.VECTOR_Z_PLUS.setText(_translate("MainWindow", "+"))
        self.VECTOR_X_MINUS.setText(_translate("MainWindow", "-"))
        self.VECTOR_Z_MINUS.setText(_translate("MainWindow", "-"))
        self.VECTOR_Y_MINUS.setText(_translate("MainWindow", "-"))
        self.ROTATION_RX_PLUS.setText(_translate("MainWindow", "+"))
        self.ROTATION_RY_MINUS.setText(_translate("MainWindow", "-"))
        self.label_35.setText(_translate("MainWindow", "Rotation"))
        self.ROTATION_RZ_PLUS.setText(_translate("MainWindow", "+"))
        self.ROTATION_RX_MINUS.setText(_translate("MainWindow", "-"))
        self.ROTATION_RZ_MINUS.setText(_translate("MainWindow", "-"))
        self.ROTATION_RY_PLUS.setText(_translate("MainWindow", "+"))
        self.TCP_Z_MINUS.setText(_translate("MainWindow", "-"))
        self.TCP_RY_MINUS.setText(_translate("MainWindow", "-"))
        self.TCP_RZ_PLUS.setText(_translate("MainWindow", "+"))
        self.TCP_RX_MINUS.setText(_translate("MainWindow", "-"))
        self.TCP_Y_MINUS.setText(_translate("MainWindow", "-"))
        self.TCP_RZ_MINUS.setText(_translate("MainWindow", "-"))
        self.TCP_X_MINUS.setText(_translate("MainWindow", "-"))
        self.TCP_RY_PLUS.setText(_translate("MainWindow", "+"))
        self.TCP_Y_PLUS.setText(_translate("MainWindow", "+"))
        self.TCP_X_PLUS.setText(_translate("MainWindow", "+"))
        self.TCP_RX_PLUS.setText(_translate("MainWindow", "+"))
        self.TCP_Z_PLUS.setText(_translate("MainWindow", "+"))
        self.label_38.setText(_translate("MainWindow", "X"))
        self.label_39.setText(_translate("MainWindow", "Y"))
        self.label_40.setText(_translate("MainWindow", "Z"))
        self.label_41.setText(_translate("MainWindow", "RZ"))
        self.label_42.setText(_translate("MainWindow", "RX"))
        self.label_43.setText(_translate("MainWindow", "RY"))
        self.OBJ_PUB_BTN.setText(_translate("MainWindow", "PUB"))
        self.HOME_BTN.setText(_translate("MainWindow", "HOME"))
        self.ZERO_BTN.setText(_translate("MainWindow", "ZERO"))
        self.label_44.setText(_translate("MainWindow", "X"))
        self.label_45.setText(_translate("MainWindow", "TCP offset"))
        self.TCP_OFFSET_PUB_BTN.setText(_translate("MainWindow", "PUB"))
        self.label_46.setText(_translate("MainWindow", "Y"))
        self.label_47.setText(_translate("MainWindow", "Z"))
        self.PICK_N_PLACE_DEMO_BTN.setText(_translate("MainWindow", "DEMO"))
        self.GET_TASK_UNIT_BTN.setText(_translate("MainWindow", "Get"))
        self.label_48.setText(_translate("MainWindow", "PICKIT"))
        self.COORDINATE_WORLD_BTN.setText(_translate("MainWindow", "WORLD"))
        self.COORDINATE_TCP_BTN.setText(_translate("MainWindow", "TCP"))
