# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/controller.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(616, 414)
        Dialog.setMinimumSize(QtCore.QSize(586, 0))
        Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.slide_joint_2 = QtWidgets.QSlider(Dialog)
        self.slide_joint_2.setMinimum(-180)
        self.slide_joint_2.setMaximum(180)
        self.slide_joint_2.setOrientation(QtCore.Qt.Horizontal)
        self.slide_joint_2.setObjectName("slide_joint_2")
        self.gridLayout.addWidget(self.slide_joint_2, 2, 1, 1, 1)
        self.slide_joint_1 = QtWidgets.QSlider(Dialog)
        self.slide_joint_1.setMinimum(-180)
        self.slide_joint_1.setMaximum(180)
        self.slide_joint_1.setOrientation(QtCore.Qt.Horizontal)
        self.slide_joint_1.setObjectName("slide_joint_1")
        self.gridLayout.addWidget(self.slide_joint_1, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.slide_joint_5 = QtWidgets.QSlider(Dialog)
        self.slide_joint_5.setMinimum(-180)
        self.slide_joint_5.setMaximum(180)
        self.slide_joint_5.setOrientation(QtCore.Qt.Horizontal)
        self.slide_joint_5.setObjectName("slide_joint_5")
        self.gridLayout.addWidget(self.slide_joint_5, 8, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.slide_joint_6 = QtWidgets.QSlider(Dialog)
        self.slide_joint_6.setMinimum(-180)
        self.slide_joint_6.setMaximum(180)
        self.slide_joint_6.setOrientation(QtCore.Qt.Horizontal)
        self.slide_joint_6.setObjectName("slide_joint_6")
        self.gridLayout.addWidget(self.slide_joint_6, 10, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.slide_joint_3 = QtWidgets.QSlider(Dialog)
        self.slide_joint_3.setMinimum(-180)
        self.slide_joint_3.setMaximum(180)
        self.slide_joint_3.setOrientation(QtCore.Qt.Horizontal)
        self.slide_joint_3.setObjectName("slide_joint_3")
        self.gridLayout.addWidget(self.slide_joint_3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.slide_joint_4 = QtWidgets.QSlider(Dialog)
        self.slide_joint_4.setMinimum(-180)
        self.slide_joint_4.setMaximum(180)
        self.slide_joint_4.setOrientation(QtCore.Qt.Horizontal)
        self.slide_joint_4.setObjectName("slide_joint_4")
        self.gridLayout.addWidget(self.slide_joint_4, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.value_joint_1 = QtWidgets.QDoubleSpinBox(Dialog)
        self.value_joint_1.setMinimum(-180.0)
        self.value_joint_1.setMaximum(180.0)
        self.value_joint_1.setObjectName("value_joint_1")
        self.gridLayout.addWidget(self.value_joint_1, 0, 2, 1, 1)
        self.value_joint_2 = QtWidgets.QDoubleSpinBox(Dialog)
        self.value_joint_2.setMinimum(-180.0)
        self.value_joint_2.setMaximum(180.0)
        self.value_joint_2.setObjectName("value_joint_2")
        self.gridLayout.addWidget(self.value_joint_2, 2, 2, 1, 1)
        self.value_joint_3 = QtWidgets.QDoubleSpinBox(Dialog)
        self.value_joint_3.setMinimum(-180.0)
        self.value_joint_3.setMaximum(180.0)
        self.value_joint_3.setObjectName("value_joint_3")
        self.gridLayout.addWidget(self.value_joint_3, 4, 2, 1, 1)
        self.value_joint_4 = QtWidgets.QDoubleSpinBox(Dialog)
        self.value_joint_4.setMinimum(-180.0)
        self.value_joint_4.setMaximum(180.0)
        self.value_joint_4.setObjectName("value_joint_4")
        self.gridLayout.addWidget(self.value_joint_4, 6, 2, 1, 1)
        self.value_joint_5 = QtWidgets.QDoubleSpinBox(Dialog)
        self.value_joint_5.setMinimum(-180.0)
        self.value_joint_5.setMaximum(180.0)
        self.value_joint_5.setObjectName("value_joint_5")
        self.gridLayout.addWidget(self.value_joint_5, 8, 2, 1, 1)
        self.value_joint_6 = QtWidgets.QDoubleSpinBox(Dialog)
        self.value_joint_6.setMinimum(-180.0)
        self.value_joint_6.setMaximum(180.0)
        self.value_joint_6.setObjectName("value_joint_6")
        self.gridLayout.addWidget(self.value_joint_6, 10, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Joint 2"))
        self.label.setText(_translate("Dialog", "Joint 1"))
        self.label_6.setText(_translate("Dialog", "Joint 6"))
        self.label_3.setText(_translate("Dialog", "Joint 3"))
        self.label_4.setText(_translate("Dialog", "Joint 4"))
        self.label_5.setText(_translate("Dialog", "Joint 5"))
